name = "InfrastructureSickos"
author = "InfrastructureSickos"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7809653b394a47a911bb29a2d68981abe64533515374bf99f8fa5b87b3939362"

[versions]
forge = "47.3.12"
minecraft = "1.20.1"
